name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Installing Packages
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
        
    - name: Building Package
      uses: CultureHQ/actions-yarn@master
      with:
        args: build
      env:
        CI: true
    - name: ZEIT Now Deployment
      uses: amondnet/now-deployment@v1
      with:
        zeit-token: ${{ secrets.ZEIT_TOKEN }}
        github-token: ${{ secrets.GTIHUB_TOKEN }}
        now-args: '--prod'
